### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by ByeongHunKim** [ByeongHunKim/NestJS-boilerplate#5]
## todo list

- [x] generate new nest project
- [x] clean tha project
- [x] infra set up (postgres DB)
- [x] swagger docs
- [x] add commands in package json about setting prisma
- [x] env setup ( config )
- [x] create auth module with basic controller and service
- [x] init prisma schema with module and service
- [x] work on auth service ( implement jwt, dto with validation pipe )
- [x] jwt strategy and guard and allow cookies
- [x] create users module with controller and service
- [x] wrap up and conclusions
- [x] env injection setting in package.json 
- [ ] jest.config.js setting
